@host = https://localhost
@port = 5001
@apiHost = {{host}}:{{port}}

GET {{apiHost}}/api/restaurants
Accept: application/json

###
GET {{apiHost}}/api/restaurants/2004
Accept: application/json

###
POST {{apiHost}}/api/restaurants
Content-Type: application/json

{
    "Name": "Owner2 restaurant2",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Mexican",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###
DELETE {{apiHost}}/api/restaurants/1004
Accept: application/json


###
PATCH  {{apiHost}}/api/restaurants/2004
Content-Type: application/json

{
  "Name": "Sample patch",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}